name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main  # Run workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version used in your Next.js app

      - name: Install dependencies
        run: npm install

      - name: Build Next.js application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next  # Adjust path if using custom output directories

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          # Configure SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Prepare application directory on EC2
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo mkdir -p /var/www/nextjs-app
            sudo chown -R $USER:$USER /var/www/nextjs-app
            sudo chmod -R 755 /var/www/nextjs-app
          EOF

          # Copy build files to EC2's /tmp directory
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r .next $USER@$HOST:/tmp/nextjs-build

          # Move build files from /tmp to the target directory and restart the app
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo mv /tmp/nextjs-build/* /var/www/nextjs-app/
            cd /var/www/nextjs-app

            # Install dependencies and start or restart the app with PM2
            npm install
            pm2 restart app || pm2 start npm --name "app" -- start
          EOF
